---

multi_az: no
backup_retention_period: 2
auto_minor_version_upgrade: true
db_engine: mysql
db_engine_postgres: postgres
db_instance_class: db.t3.micro

# Disk
max_allocated_storage: 100

# Network
db_subnet_group_name: "zzz"
vpc_security_group_ids:
  - sg-zzz

# Monitoring
enable_performance_insights: false
monitoring_role_arn: "arn:aws:iam::zzz"

# Security
kms_key_id: "zzz"

# Tags
db_environment: "hom"
dbpm_db_environment: 'QA'

...