---

multi_az: yes
backup_retention_period: 20
auto_minor_version_upgrade: false
db_engine: mysql
db_engine_postgres: postgres
db_instance_class: db.t3.medium

# Disk
max_allocated_storage: 1000

# Network
db_subnet_group_name: "zzz"
vpc_security_group_ids:
  - sg-zzz

# Monitoring
enable_performance_insights: yes
monitoring_role_arn: "arn:aws:iam::zzz"

# Security
kms_key_id: "zzz"

# Tags
db_environment: "prd"
dbpm_db_environment: 'PROD'

...