---

multi_az: no
backup_retention_period: 2
auto_minor_version_upgrade: true
db_engine: mysql
db_engine_postgres: postgres
db_instance_class: db.t3.micro

# Disk
max_allocated_storage: 100

# Network
db_subnet_group_name: "jd-db-subnet-qa"
vpc_security_group_ids:
  - sg-0d680c37e411d1d07

# Monitoring
enable_performance_insights: false
monitoring_role_arn: "arn:aws:iam::479550711906:role/rds-monitoring-role"

# Security
kms_key_id: "d5f4f415-e6eb-49ff-baaa-e15c0260a8ae"

# Tags
db_environment: "hom"

...